[tool.flake8]
extend-ignore = "E501,W503"

[tool.isort]
profile = "black"

[tool.poetry]
name = "ts2mp4"
version = "2022.07.29.1"
description = ""
authors = ["dmingn <dmingn@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = {extras = ["pyproject"], version = "*"}
mypy = "*"
pydocstyle = "*"
pyproject-flake8 = "*"

[tool.poetry.scripts]
ts2mp4 = "ts2mp4.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
