[tool.isort]
profile = "black"

[tool.poetry]
name = "ts2mp4"
version = "2022.07.29.1"
description = ""
authors = ["dmingn <dmingn@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.16.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = {extras = ["pyproject"], version = "^5.11.5"}
flake8 = "^7.3.0"
mypy = "^1.4.1"
pydocstyle = "^6.3.0"
pytest = "^8.4.1"
pytest-mock = "^3.14.1"

[tool.poetry.scripts]
ts2mp4 = "ts2mp4.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = [".venv", "build", "dist"]
