[tool.flake8]
extend-ignore = "E501,W503"

[tool.isort]
profile = "black"

[tool.poetry]
name = "ts2mp4"
version = "2022.07.29.1"
description = ""
authors = ["dmingn <dmingn@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
isort = {extras = ["pyproject"], version = "^5.11.5"}
mypy = "^1.4"
pydocstyle = "^6.3.0"
pyproject-flake8 = "^5.0.4.post1"

[tool.poetry.scripts]
ts2mp4 = "ts2mp4.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
