name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: linuxserver/ffmpeg:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install pipx
        run: apt update && apt install -y pipx && pipx ensurepath

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version-file: ".python-version"
          cache: "poetry"

      - name: Check lock file consistency
        run: poetry check --lock

      - name: Install dependencies
        run: poetry sync

      - name: Generate test assets
        run: make tests/assets/test_video.ts

      - name: Check formatting with black
        run: poetry run black --check .

      - name: Check import order with isort
        run: poetry run isort --check .

      - name: Lint with flake8
        run: poetry run flake8 .

      - name: Check types with mypy
        run: poetry run mypy .

      - name: Run tests with pytest
        run: poetry run pytest
